<?php
/**
 *   (Auto Generated Class)
 *   BlogsTableDTO class
 *   
 *   generated by CharcoalPHP ver.2.20.0.148
 *   
 *   PHP version 5
 *   
 *   @author     CharcoalPHP Development Team
 *   @copyright  2008 - 2013 CharcoalPHP Development Team
 */
class BlogsTableDTO extends Charcoal_TableDTO
{
    public $blog_id;
    public $blog_category_id;
    public $blog_name;
    public $post_total;
}

return __FILE__;	// end of file
