<?php
/**
 *   (Auto Generated Class)
 *   BlogsTableModel class
 *   
 *   generated by CharcoalPHP ver.2.20.0.148
 *   
 *   PHP version 5
 *   
 *   @author     CharcoalPHP Development Team
 *   @copyright  2008 - 2013 CharcoalPHP Development Team
 */
class BlogsTableModel extends Charcoal_DefaultTableModel
{
    public $___table_name      = 'blogs';

    public $blog_id                       = '@field @type:int(11) @pk @insert:no @update:no @serial';
    public $blog_category_id              = '@field @type:int(11) @insert:value @update:value';
    public $blog_name                     = '@field @type:varchar(255) @insert:value @update:value';
    public $post_total                    = '@field @type:int(11) @insert:value @update:value';

	// returns model's own DTO
    public function createDTO()
    {
        return new BlogsTableDTO();
    }
}

return __FILE__;	// end of file
