<?php
/**
 *   (Auto Generated Class)
 *   PostTableModel class
 *   
 *   generated by CharcoalPHP ver.2.8.18.95
 *   
 *   PHP version 5
 *   
 *   @author     CharcoalPHP Development Team
 *   @copyright  2008 - 2013 CharcoalPHP Development Team
 */
class CommentTableModel extends Charcoal_DefaultTableModel
{
    public $___table_name      = 'comments';

	public $post            = '@relation @target:posts @linkage:inner[post_id] @extract:field';

    public $comment_id      = '@field @type:int(11) @pk @insert:no @update:no @serial';
    public $post_id         = '@field @type:int(11) @insert:value @update:value @fk:posts';
    public $comment_title   = '@field @type:text @insert:value @update:value';
    public $comment_body    = '@field @type:text @insert:value @update:value';
    public $comment_user    = '@field @type:vachar(255) @insert:value @update:value';

	// returns model's own DTO
    public function createDTO( $values = array() )
    {
        return new CommentTableDTO( $values );
    }
}

return __FILE__;	// end of file
