<?php
/**
* タスク
*
* PHP version 5
*
* @package    renderers
* @author     stk2k <stk2k@sazysoft.com>
* @copyright  2008 stk2k, sazysoft
*/

class GenerateModelTask extends Charcoal_Task
{
    const DIR_MODE        = '666';
    const SPACE_COUNT     = 30;

    /**
     * process event
     *
     * @param Charcoal_IEventContext $context
     *
     * @return boolean|Charcoal_Boolean
     */
    public function processEvent( $context )
    {
        /** @var GenerateModelEvent $event */
        $event   = $context->getEvent();

        // get event parameters
        $db_name       = $event->getDatabase();
        $table_name    = $event->getTable();
        $out_dir       = $event->getTargetDir();

        $entity = Charcoal_System::pascalCase( $table_name );
        $config_key = Charcoal_System::snakeCase( $table_name );

        $table_model_class_name = "{$entity}TableModel";
        $table_dto_class_name = "{$entity}TableDTO";

        /** @var Charcoal_SmartGateway $gw */
        $gw = $context->getComponent( 'smart_gateway@:charcoal:db' );

        //=======================================
        // Mmake output directory
        //=======================================
        $out_dir = $this->prepareOutputDirectory( $out_dir );

        //=======================================
        // confirm if the table exists
        //=======================================
        $sql = "SELECT count(*) FROM information_schema.COLUMNS WHERE TABLE_NAME = ? AND TABLE_SCHEMA = ? ";
        $params = array( $table_name, $db_name );
        $count = $gw->queryValue( NULL, $sql, $params );

        if ( $count < 1 ){
            print "[ERROR] Specified table '$table_name' does not exist in schema: '$db_name'. Please check your database settings." . PHP_EOL;
            return b(true);
        }

        //=======================================
        // Retrieve column information
        //=======================================
        $sql = "SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_KEY, COLUMN_DEFAULT, EXTRA ";
        $sql .= " FROM information_schema.COLUMNS WHERE TABLE_NAME = ? AND TABLE_SCHEMA = ? ";
        $params = array( $table_name, $db_name );
        $colmn_attr_list = $gw->query( NULL, $sql, $params );

        //=======================================
        // Genarate  table model file
        //=======================================

        $this->generateTableModelFile( $table_name, $colmn_attr_list, $table_model_class_name, $table_dto_class_name, $out_dir );

        //=======================================
        // Genarate table DTO file
        //=======================================

        $this->generateTableDtolFile( $colmn_attr_list, $table_dto_class_name, $out_dir );

        //=======================================
        // Genarate  config file
        //=======================================

        $this->generateTableConfigFile( $table_model_class_name, $config_key, $out_dir );

        return b(true);
    }

    /**
     * prepare output directory
     *
     * @param string $out_dir
     *
     * @return Charcoal_File
     */
    private function prepareOutputDirectory( $out_dir )
    {
        $out_dir = new Charcoal_File( $out_dir );

        $out_dir->makeDirectory( self::DIR_MODE );
    }

    /**
     * generate table model file
     *
     * @param string $table_name
     * @param array $colmn_attr_list
     * @param string $table_model_class_name
     * @param string $table_dto_class_name
     * @param string $out_dir
     */
    private function generateTableModelFile( $table_name, $colmn_attr_list, $table_model_class_name, $table_dto_class_name, $out_dir )
    {
        $lines = NULL;

        $lines[] = "<?php";
        $lines[] = "/**";
        $lines[] = " *   (Auto Generated Class)";
        $lines[] = " *   {$table_model_class_name} class";
        $lines[] = " *   ";
        $lines[] = " *   generated by CharcoalPHP ver." . Charcoal_Framework::getVersion();
        $lines[] = " *   ";
        $lines[] = " *   @author     your name";
        $lines[] = " *   @copyright  ";
        $lines[] = " */";
        $lines[] = "class {$table_model_class_name} extends Charcoal_DefaultTableModel";
        $lines[] = "{";
        $lines[] = "    public \$___table_name      = '{$table_name}';";
        $lines[] = "";

        foreach( $colmn_attr_list as $colmn_attr ){
            $field     = $colmn_attr['COLUMN_NAME'];
            $type      = $colmn_attr['COLUMN_TYPE'];
            //$null      = $colmn_attr['IS_NULLABLE'];
            $key       = $colmn_attr['COLUMN_KEY'];
            //$default   = $colmn_attr['COLUMN_DEFAULT'];
            //$extra     = $colmn_attr['EXTRA'];

            $spaces = str_repeat( " ", self::SPACE_COUNT - strlen($field) );

            if ( $key == "PRI" ){
                $lines[] = "    public \${$field}{$spaces}= '@field @type:$type @pk @insert:no @update:no @serial';";
            }
            else{
                $lines[] = "    public \${$field}{$spaces}= '@field @type:$type @insert:value @update:value';";
            }
//echo "Field:$field Type:$type Null:$null Key:$key Default:$default Extra:$extra" . PHP_EOL;
        }

        $lines[] = "";
        $lines[] = "\t// returns model's own DTO";
        $lines[] = "    public function createDTO( \$values = array() )";
        $lines[] = "    {";
        $lines[] = "        return new {$table_dto_class_name}( \$values );";
        $lines[] = "    }";
        $lines[] = "}";
        $lines[] = "";
        $lines[] = "return __FILE__;    // end of file";

        $file_name = $table_model_class_name . ".class.php";
        $outfile = new Charcoal_File( $file_name, $out_dir );
        Charcoal_FileSystemUtil::outputFile( $outfile, $lines );

        print "{$outfile} was successfully generated." . PHP_EOL;
    }

    /**
     * generate table model file
     *
     * @param array $colmn_attr_list
     * @param string $table_dto_class_name
     * @param string $out_dir
     */
    private function generateTableDtolFile( $colmn_attr_list, $table_dto_class_name, $out_dir )
    {
        $lines = NULL;

        $lines[] = "<?php";
        $lines[] = "/**";
        $lines[] = " *   (Auto Generated Class)";
        $lines[] = " *   {$table_dto_class_name} class";
        $lines[] = " *   ";
        $lines[] = " *   generated by CharcoalPHP ver." . Charcoal_Framework::getVersion();
        $lines[] = " *   ";
        $lines[] = " *   PHP version 5";
        $lines[] = " *   ";
        $lines[] = " *   @author     CharcoalPHP Development Team";
        $lines[] = " *   @copyright  2008 stk2k, sazysoft";
        $lines[] = " */";
        $lines[] = "class {$table_dto_class_name} extends Charcoal_TableDTO";
        $lines[] = "{";

        foreach( $colmn_attr_list as $colmn_attr ){
            $field     = $colmn_attr['COLUMN_NAME'];
            //$type      = $colmn_attr['COLUMN_TYPE'];
            //$null      = $colmn_attr['IS_NULLABLE'];
            //$key       = $colmn_attr['COLUMN_KEY'];
            //$default   = $colmn_attr['COLUMN_DEFAULT'];
            //$extra     = $colmn_attr['EXTRA'];

            $lines[] = "    public \${$field};";
        }

        $lines[] = "}";
        $lines[] = "";
        $lines[] = "return __FILE__;    // end of file";

        $file_name = $table_dto_class_name . ".class.php";
        $outfile = new Charcoal_File( $file_name, $out_dir );
        Charcoal_FileSystemUtil::outputFile( $outfile, $lines );

        print "{$outfile} was successfully generated." . PHP_EOL;
    }

    /**
     * generate table model file
     *
     * @param string $table_model_class_name
     * @param string $config_key
     * @param string $out_dir
     */
    private function generateTableConfigFile( $table_model_class_name, $config_key, $out_dir )
    {
        $lines = NULL;

        $lines[] = "class_name    = {$table_model_class_name}";

        $file_name = $config_key . ".table_model.ini";
        $outfile = new Charcoal_File( $file_name, $out_dir );
        Charcoal_FileSystemUtil::outputFile( $outfile, $lines );

        print "{$outfile} was successfully generated." . PHP_EOL;

    }
}

return __FILE__;