<?php
/**
 *   (Auto Generated Class)
 *   BlogCategoryTableDTO class
 *   
 *   generated by CharcoalPHP ver.2.5.3.49
 *   
 *   PHP version 5
 *   
 *   @author     CharcoalPHP Development Team
 *   @copyright  2008 stk2k, sazysoft
 */
class BlogCategoryTableDTO extends Charcoal_TableDTO
{
    public $blog_category_id;
    public $blog_category_name;
}

return __FILE__;    // end of file
