<?php
/**
 *   (Auto Generated Class)
 *   BlogTableDTO class
 *   
 *   generated by CharcoalPHP ver.2.5.3.49
 *   
 *   PHP version 5
 *   
 *   @author     CharcoalPHP Development Team
 *   @copyright  2008 - 2013 CharcoalPHP Development Team
 */
class BlogTableDTO extends Charcoal_TableDTO
{
    public $blog_id;
    public $blog_category_id;
    public $blog_name;
    public $post_total;
    public $created_date;
    public $modified_date;
}

return __FILE__;    // end of file
