<?php
/**
 *   (Auto Generated Class)
 *   Item2TableDTO class
 *   
 *   generated by CharcoalPHP ver.2.64.1.258
 *   
 *   PHP version 5
 *   
 *   @author     CharcoalPHP Development Team
 *   @copyright  2008 stk2k, sazysoft
 */
class Item2TableDTO extends Charcoal_TableDTO
{
    public $item_id;
    public $item_name;
    public $price;
    public $stock;
    public $created_date;
    public $modified_date;
}

return __FILE__;    // end of file
