<?php
/**
 *   (Auto Generated Class)
 *   ItemsTableDTO class
 *   
 *   generated by CharcoalPHP ver.2.63.3.256
 *   
 *   PHP version 5
 *   
 *   @author     CharcoalPHP Development Team
 *   @copyright  2008 stk2k, sazysoft
 */
class ItemTableDTO extends Charcoal_TableDTO
{
    public $item_name;
    public $price;
    public $stock;
}

return __FILE__;    // end of file
