<?php
/**
 *   (Auto Generated Class)
 *   BlogTableDTO class
 *   
 *   generated by CharcoalPHP ver.2.5.3.49
 *   
 *   PHP version 5
 *   
 *   @author     CharcoalPHP Development Team
 *   @copyright  2008 - 2013 CharcoalPHP Development Team
 */
class PostTableDTO extends Charcoal_TableDTO
{
    public $post_id;
    public $blog_id;
    public $post_title;
    public $post_body;
    public $post_user;
    public $favorite;
}

return __FILE__;    // end of file
