<?php
/**
 *   (Auto Generated Class)
 *   TestTableDTO class
 *   
 *   generated by CharcoalPHP ver.2.40.0.201
 *   
 *   PHP version 5
 *   
 *   @author     CharcoalPHP Development Team
 *   @copyright  2008 stk2k, sazysoft
 */
class TestTableDTO extends Charcoal_TableDTO
{
    public $id;
    public $name;
    public $price;
}

return __FILE__;	// end of file
