<?php
/**
 *   (Auto Generated Class)
 *   ItemsTableModel class
 *   
 *   generated by CharcoalPHP ver.2.63.3.256
 *   
 *   @author     your name
 *   @copyright  
 */
class ItemTableModel extends Charcoal_DefaultTableModel
{
    public $___table_name      = 'item';

    public $item_name                     = '@field @type:text @insert:value @update:value';
    public $price                         = '@field @type:int(11) @insert:value @update:value';
    public $stock                         = '@field @type:int(11) @insert:value @update:value';

	// returns model's own DTO
    public function createDTO( $values = array() )
    {
        return new ItemTableDTO( $values );
    }
}

return __FILE__;    // end of file
