<?php
/**
 *   (Auto Generated Class)
 *   TestTableModel class
 *   
 *   generated by CharcoalPHP ver.2.40.0.201
 *   
 *   PHP version 5
 *   
 *   @author     CharcoalPHP Development Team
 *   @copyright  2008 stk2k, sazysoft
 */
class TestTableModel extends Charcoal_DefaultTableModel
{
    public $___table_name      = 'test';

    public $id                            = '@field @type:int(11) @pk @insert:no @update:no @serial';
    public $name                          = '@field @type:text @insert:value @update:value';
    public $price                         = '@field @type:int(11) @insert:value @update:value';

    // returns model's own DTO
    public function createDTO( $values = array() )
    {
        return new TestTableDTO( $values );
    }
}

return __FILE__;    // end of file
