<?php
/**
 *   (Auto Generated Class)
 *   HelloWorldTask class
 *   
 *   generated by CharcoalPHP ver.2.48.0.218
 *   
 *   @author     your name
 *   @copyright  
 */
class HelloWorldTask extends Charcoal_Task
{
    /**
     * Process user/system event
     *
     * @param Charcoal_EventContext $context       Event context
     * 
     * @return bool|Charcoal_Boolean       Return true if the event is processed. Or you can 
     *        return false if another task should process the event.
     */
    public function processEvent( $context )
    {
        $request   = $context->getRequest();
        $response  = $context->getResponse();
        $sequence  = $context->getSequence();
        $procedure = $context->getProcedure();
        
        // TODO: write processing event code here
        $name = $request->getString('name', 'john');
        
        return b(true);
    }
}
