<?php
/**
 *   (Auto Generated Class)
 *   ColumnsTableModel class
 *   
 *   generated by CharcoalPHP ver.2.63.3.256
 *   
 *   @author     your name
 *   @copyright  
 */
class ColumnsTableModel extends Charcoal_DefaultTableModel
{
    public $___table_name      = 'columns';

    public $TABLE_CATALOG                 = '@field @type:varchar(512) @insert:value @update:value';
    public $TABLE_SCHEMA                  = '@field @type:varchar(64) @insert:value @update:value';
    public $TABLE_NAME                    = '@field @type:varchar(64) @insert:value @update:value';
    public $COLUMN_NAME                   = '@field @type:varchar(64) @insert:value @update:value';
    public $ORDINAL_POSITION              = '@field @type:bigint(21) unsigned @insert:value @update:value';
    public $COLUMN_DEFAULT                = '@field @type:longtext @insert:value @update:value';
    public $IS_NULLABLE                   = '@field @type:varchar(3) @insert:value @update:value';
    public $DATA_TYPE                     = '@field @type:varchar(64) @insert:value @update:value';
    public $CHARACTER_MAXIMUM_LENGTH      = '@field @type:bigint(21) unsigned @insert:value @update:value';
    public $CHARACTER_OCTET_LENGTH        = '@field @type:bigint(21) unsigned @insert:value @update:value';
    public $NUMERIC_PRECISION             = '@field @type:bigint(21) unsigned @insert:value @update:value';
    public $NUMERIC_SCALE                 = '@field @type:bigint(21) unsigned @insert:value @update:value';
    public $DATETIME_PRECISION            = '@field @type:bigint(21) unsigned @insert:value @update:value';
    public $CHARACTER_SET_NAME            = '@field @type:varchar(32) @insert:value @update:value';
    public $COLLATION_NAME                = '@field @type:varchar(32) @insert:value @update:value';
    public $COLUMN_TYPE                   = '@field @type:longtext @insert:value @update:value';
    public $COLUMN_KEY                    = '@field @type:varchar(3) @insert:value @update:value';
    public $EXTRA                         = '@field @type:varchar(30) @insert:value @update:value';
    public $PRIVILEGES                    = '@field @type:varchar(80) @insert:value @update:value';
    public $COLUMN_COMMENT                = '@field @type:varchar(1024) @insert:value @update:value';

	// returns model's own DTO
    public function createDTO( $values = array() )
    {
        return new ColumnsTableDTO( $values );
    }
}

return __FILE__;    // end of file
