<?php
/**
 *   (Auto Generated Class)
 *   ColumnsTableDTO class
 *   
 *   generated by CharcoalPHP ver.2.63.3.256
 *   
 *   PHP version 5
 *   
 *   @author     CharcoalPHP Development Team
 *   @copyright  2008 stk2k, sazysoft
 */
class ColumnsTableDTO extends Charcoal_TableDTO
{
    public $TABLE_CATALOG;
    public $TABLE_SCHEMA;
    public $TABLE_NAME;
    public $COLUMN_NAME;
    public $ORDINAL_POSITION;
    public $COLUMN_DEFAULT;
    public $IS_NULLABLE;
    public $DATA_TYPE;
    public $CHARACTER_MAXIMUM_LENGTH;
    public $CHARACTER_OCTET_LENGTH;
    public $NUMERIC_PRECISION;
    public $NUMERIC_SCALE;
    public $DATETIME_PRECISION;
    public $CHARACTER_SET_NAME;
    public $COLLATION_NAME;
    public $COLUMN_TYPE;
    public $COLUMN_KEY;
    public $EXTRA;
    public $PRIVILEGES;
    public $COLUMN_COMMENT;
}

return __FILE__;    // end of file
