<?php
/**
 *   (Auto Generated Class)
 *   CommentTableDTO class
 *   
 *   generated by CharcoalPHP ver.2.5.3.49
 *   
 *   PHP version 5
 *   
 *   @author	 CharcoalPHP Development Team
 *   @copyright  2008 - 2013 CharcoalPHP Development Team
 */
class CommentTableDTO extends Charcoal_TableDTO
{
	public $post;

	public $comment_id;
	public $post_id;
	public $comment_title;
	public $comment_body;
	public $comment_user;

}

return __FILE__;	// end of file
